nome = str(input('Digite seu nome completo: ')).strip()
print('É um prazer te conhecer, {}!'.format(nome))
nome2 = nome.split()
print('Seu primeiro nome é: {}'.format(nome2[0]))
print('Seu último nome é: {}'.format(nome2[-1]))